
package com.nttdata.ofertassecundarias.model.client.dto;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MTHHttpGet", targetNamespace = "http://tempuri.org/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MTHHttpGet {


    /**
     * 
     * @param password
     * @param telOrigen
     * @param mensajeSMS
     * @param login
     * @param telDestino
     */
    @WebMethod(operationName = "NotificaConsultaSMS")
    public void notificaConsultaSMS(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Login")
        String login,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Password")
        String password,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "TelOrigen")
        String telOrigen,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "TelDestino")
        String telDestino,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "MensajeSMS")
        String mensajeSMS);

    /**
     * 
     * @param password
     * @param telOrigen
     * @param mensajeSMS
     * @param login
     * @param telDestino
     */
    @WebMethod(operationName = "EnvioSMS")
    public void envioSMS(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Login")
        String login,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Password")
        String password,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "TelOrigen")
        String telOrigen,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "TelDestino")
        String telDestino,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "MensajeSMS")
        String mensajeSMS);

    /**
     * 
     * @param dni
     * @return
     *     returns com.nttdata.ofertassecundarias.model.dto.client.MTHResponse
     */
    @WebMethod(operationName = "OperacionMTH")
    @WebResult(name = "MTHResponse", targetNamespace = "http://tempuri.org/", partName = "Body")
    public MTHResponse operacionMTH(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "dni")
        String dni);

}
