
package com.nttdata.ofertassecundarias.model.client.dto;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MTHSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MTHSoap {


    /**
     * 
     * @param password
     * @param telOrigen
     * @param mensajeSMS
     * @param login
     * @param telDestino
     */
    @WebMethod(operationName = "NotificaConsultaSMS", action = "http://tempuri.org/NotificaConsultaSMS")
    @RequestWrapper(localName = "NotificaConsultaSMS", targetNamespace = "http://tempuri.org/", className = "com.nttdata.ofertassecundarias.model.dto.client.NotificaConsultaSMS")
    @ResponseWrapper(localName = "NotificaConsultaSMSResponse", targetNamespace = "http://tempuri.org/", className = "com.nttdata.ofertassecundarias.model.dto.client.NotificaConsultaSMSResponse")
    public void notificaConsultaSMS(
        @WebParam(name = "Login", targetNamespace = "http://tempuri.org/")
        String login,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "TelOrigen", targetNamespace = "http://tempuri.org/")
        String telOrigen,
        @WebParam(name = "TelDestino", targetNamespace = "http://tempuri.org/")
        String telDestino,
        @WebParam(name = "MensajeSMS", targetNamespace = "http://tempuri.org/")
        String mensajeSMS);

    /**
     * 
     * @param password
     * @param telOrigen
     * @param mensajeSMS
     * @param login
     * @param telDestino
     */
    @WebMethod(operationName = "EnvioSMS", action = "http://tempuri.org/EnvioSMS")
    @RequestWrapper(localName = "EnvioSMS", targetNamespace = "http://tempuri.org/", className = "com.nttdata.ofertassecundarias.model.dto.client.EnvioSMS")
    @ResponseWrapper(localName = "EnvioSMSResponse", targetNamespace = "http://tempuri.org/", className = "com.nttdata.ofertassecundarias.model.dto.client.EnvioSMSResponse")
    public void envioSMS(
        @WebParam(name = "Login", targetNamespace = "http://tempuri.org/")
        String login,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "TelOrigen", targetNamespace = "http://tempuri.org/")
        String telOrigen,
        @WebParam(name = "TelDestino", targetNamespace = "http://tempuri.org/")
        String telDestino,
        @WebParam(name = "MensajeSMS", targetNamespace = "http://tempuri.org/")
        String mensajeSMS);

    /**
     * 
     * @param dni
     * @return
     *     returns com.nttdata.ofertassecundarias.model.dto.client.MTHResponse
     */
    @WebMethod(operationName = "OperacionMTH", action = "http://tempuri.org/OperacionMTH")
    @WebResult(name = "OperacionMTHResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "OperacionMTH", targetNamespace = "http://tempuri.org/", className = "com.nttdata.ofertassecundarias.model.dto.client.OperacionMTH")
    @ResponseWrapper(localName = "OperacionMTHResponse", targetNamespace = "http://tempuri.org/", className = "com.nttdata.ofertassecundarias.model.dto.client.OperacionMTHResponse")
    public MTHResponse operacionMTH(
        @WebParam(name = "dni", targetNamespace = "http://tempuri.org/")
        String dni);

}
